---
title: "Additional Predictor with Maximum Effect Size"
author: Tingting Zhan
date: today
format: 
  html:
    page-layout: full
    html-math-method: katex
number-sections: true
toc: true
toc-location: left
toc-depth: 4
toc-title: ''
editor: source
bibliography: maxEff.bib
knitr:
  opts_chunk: 
    collapse: true
    comment: "#" 
vignette: >
  %\VignetteIndexEntry{intro}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
---

# Introduction

The complete vignette of R package **`maxEff`** (v`r packageVersion('maxEff')`) 

> <https://tingtingzhan.quarto.pub/groupedhyperframe/maxEff.html>

documents the selection of one from many `numeric` predictors for a regression model, to ensure that the additional predictor has the maximum effect size.

The complete vignette exceeds the file size limit allowed on [CRAN](https://cran.r-project.org/package=maxEff). 


# Prerequisite

## Environment

Package **`maxEff`** (v`r packageVersion('maxEff')`) requires R version 4.5.0 (released 2025-04-11) or higher.  Details are provided in the [book chapter](https://tingtingzhan.quarto.pub/groupedhyperframe/appendix/about.html#sec-envir).



## Installation

Packages **`maxEff`** (v`r packageVersion('maxEff')`) can be installed using the following command.

```{r}
#| eval: false
utils::install.packages('maxEff')
```


## Dependency

The dependencies of package **`maxEff`** are detailed in the [book chapter](https://tingtingzhan.quarto.pub/groupedhyperframe/appendix/about.html#maxEff-1).

Package **`maxEff`** requires the *development versions* of the **`spatstat.*`** family of packages [@spatstat15; @spatstat05]. Installation instructions are provided in the [book chapter](https://tingtingzhan.quarto.pub/groupedhyperframe/appendix/dev.html).





<!--

## Acknowledgement

This work is supported by National Institutes of Health, U.S. Department of Health and Human Services grants

-   R01CA222847 ([I. Chervoneva](https://orcid.org/0000-0002-9104-4505), [T. Zhan](https://orcid.org/0000-0001-9971-4844), and [H. Rui](https://orcid.org/0000-0002-8778-261X))
-   R01CA253977 (H. Rui and I. Chervoneva).

-->

# References {.appendix}

::: {#refs}
:::
